# Generated by Django 3.0.12 on 2021-03-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutinformation',
            options={'verbose_name_plural': 'checkout information objects'},
        ),
    ]
