TEXTFIELD_MAX_LENGTH = 1000

ONE_TIME_PRODUCT_ID = "prod_J1t9OsPkOcKqWm"

PICTURE_WIDTH = 100

PICTURE_HEIGHT = 50

PICTURE_QUALITY = 60

PICTURE_FORMAT = 'JPEG'

REQUIRED_MESSAGE = "This field is required."
