# Generated by Django 3.0.12 on 2021-03-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210315_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofessional',
            name='doctor_specialty',
            field=models.IntegerField(choices=[('0', 'Family Medicine'), ('1', 'Internal Medicine'), ('2', 'Emergency Medicine'), ('3', 'Pediatrics')], default='1', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofessional',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalprofessional',
            name='other_specialty',
            field=models.IntegerField(choices=[('0', 'Registered Nurse'), ('1', 'Family Nurse'), ('2', 'Cardiac Nurse'), ('3', 'Anesthetist'), ('4', 'Radiologist')], default='0', null=True),
        ),
    ]
