# Generated by Django 3.0.12 on 2021-03-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210315_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofessional',
            name='staff_type',
            field=models.IntegerField(choices=[(0, 'MD'), (1, 'Nurse Practitioner'), (2, 'Physician Assistant')], default=0),
        ),
    ]
